% run_nsections_test_step2
% n_sections test with smaller dt and longer run.

clear; close all; clc;

repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repo_root, 'src')));

col_grid = ColumnGrid(1000, 20);
profile  = DepthProfile.typical(col_grid.z_centers);

% dt chosen to keep CFL lower for each n_sections case
cases = [20, 1.0;
         25, 0.4;
         30, 0.2];

for i = 1:size(cases,1)
    ns = cases(i,1);
    dt = cases(i,2);

    cfg = SimulationConfig( ...
        'n_sections', ns, ...
        't_final', 365, ...
        'delta_t', dt, ...
        'sinking_law', 'kriest_8', ...
        'ds_kernel_mode', 'sinking_law', ...
        'enable_coag', true, ...
        'enable_sinking', true, ...
        'enable_disagg', false, ...
        'proc_substeps', 20, ...
        'enable_surface_pp', true, ...
        'surface_pp_bin', 1, ...
        'surface_pp_mu', 0.1, ...
        'enable_zoo', true, ...
        'zoo_Zc', 100, ...
        'zoo_c',  1e-4, ...
        'zoo_Zf', 50, ...
        'zoo_s',  1e-4, ...
        'zoo_p',  0.3, ...
        'zoo_ic', 1);

    sim = ColumnSimulation(cfg, col_grid, profile);
    out = sim.run();
    Yf  = squeeze(out.concentrations(end, :, :));  % n_z x n_sec

    % largest populated bin at surface
    surf = Yf(1,:);
    pop  = find(surf > 1e-10);
    if ~isempty(pop)
        last_bin = pop(end);
    else
        last_bin = 0;
    end

    fprintf('n=%d  dt=%.2f  total_bv=%.4e  largest_bin=%d\n', ...
        ns, dt, sum(Yf,'all'), last_bin);
end
