% run_nsections_test
% Check n_sections convergence for the 1-D zoo run.

clear; close all; clc;

% Step 1: load source path
repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repo_root, 'src')));

% Step 2: fixed column and profile
col_grid = ColumnGrid(1000, 20);
profile  = DepthProfile.typical(col_grid.z_centers);

% Step 3: run with different n_sections
ns_list = [20, 25, 30];
tot_bv  = zeros(numel(ns_list), 1);

for i = 1:numel(ns_list)
    cfg = SimulationConfig( ...
        'n_sections', ns_list(i), ...
        't_final', 180, ...
        'delta_t', 1, ...
        'sinking_law', 'kriest_8', ...
        'ds_kernel_mode', 'sinking_law', ...
        'enable_coag', true, ...
        'enable_sinking', true, ...
        'enable_disagg', false, ...
        'proc_substeps', 20, ...
        'enable_surface_pp', true, ...
        'surface_pp_bin', 1, ...
        'surface_pp_mu', 0.1, ...
        'enable_zoo', true, ...
        'zoo_Zc', 100, ...
        'zoo_c', 1e-4, ...
        'zoo_Zf', 50, ...
        'zoo_s', 1e-4, ...
        'zoo_p', 0.3, ...
        'zoo_ic', 1);

    sim = ColumnSimulation(cfg, col_grid, profile);
    out = sim.run();
    Yf  = squeeze(out.concentrations(end, :, :));
    tot_bv(i) = sum(Yf, 'all');
    fprintf('n_sections=%d  total_bv=%.4e\n', ns_list(i), tot_bv(i));
end

% Step 4: print simple relative changes
for i = 2:numel(ns_list)
    rel = 100 * (tot_bv(i) - tot_bv(i-1)) / max(tot_bv(i-1), eps);
    fprintf('change %d->%d = %.3f%%\n', ns_list(i-1), ns_list(i), rel);
end
